clc;
clear all;
n=input('enter window length');
wn=input('enter cutoff frequency');
window1=rectwin(n+1);
b1=fir1(n,wn,window1);
[h1,w1]=freqz(b1,1,128);
subplot(3,1,1);
plot(w1/pi,20*log(abs(h1)));
title('Rectangular Window');
xlabel('normalised frequency');
ylabel('normalised gain');
grid;
window2=triang(n+1);
b2=fir1(n,wn,window2);
[h2,w2]=freqz(b2,1,128);
subplot(3,1,2);
plot(w2/pi,20*log(abs(h2)));
title('Triangular Window');
xlabel('normalised frequency');
ylabel('normalised gain');
grid;
window3=kaiser(n+1);
b3=fir1(n,wn,window3);
[h3,w3]=freqz(b3,1,128);
subplot(3,1,3);
plot(w3/pi,20*log(abs(h3)));
title('Kaiser Window');
xlabel('normalised frequency');
ylabel('normalised gain');
grid;
figure
plot(w1/pi,abs(h1),'-rx',w2/pi,abs(h2),'-go',w3/pi,abs(h3),'-.b');
hleg1 = legend('Rectangular','Triangular','Kaiser');
